networks:
  roachnet: {}

services:
  roach1:
    image: cockroachdb/cockroach:v24.3.6
    command: start --insecure --advertise-addr=roach1:26257 --join=roach1,roach2,roach3 --cluster-name=tulloroach
    healthcheck:
      interval: 10s
      retries: 5
      timeout: 5s
      test: ["CMD", "/cockroach/cockroach", "node", "status", "--insecure"]
    networks:
      roachnet:
    ports:
    - published: 8080
      target: 8080
    - published: 26257
      target: 26257
    volumes:
      - roach1_data:/cockroach/cockroach-data

  roach2:
    image: cockroachdb/cockroach:v24.3.6
    command: start --insecure --advertise-addr=roach2:26257 --join=roach1,roach2,roach3 --cluster-name=tulloroach
    networks:
      roachnet:
    volumes:
      - roach2_data:/cockroach/cockroach-data

  roach3:
    image: cockroachdb/cockroach:v24.3.6
    command: start --insecure --advertise-addr=roach3:26257 --join=roach1,roach2,roach3 --cluster-name=tulloroach
    networks:
      roachnet:
    volumes:
      - roach3_data:/cockroach/cockroach-data

  init-cluster:
    image: cockroachdb/cockroach:v24.3.6
    command: init --insecure --host=roach1:26257 --cluster-name=tulloroach
    depends_on:
      roach1:
        condition: service_started
    networks:
      roachnet:

volumes:
  roach1_data: {}
  roach2_data: {}
  roach3_data: {}
