services:
  crdb:
    image: cockroachdb/cockroach:v21.2.2
    command: start-single-node --insecure --listen-addr=0.0.0.0
    healthcheck:
      interval: 10s
      retries: 5
      timeout: 5s
      test: ["CMD", "/cockroach/cockroach", "node", "status", "--insecure"]
    ports:
    - published: 8080
      target: 8080
    - published: 26257
      target: 26257
    volumes:
    - crdb_data:/cockroach/cockroach-data

volumes:
  crdb_data: {}
